# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e0e0be54f5a9e285bd4db5d5b77b00c743dbf25f79af8db34c6ddf13878d9c2cf903c76a7d032de8d364506487b5855cdd3bdd187ecf108ede62c04e608af6a

test:
  secret_key_base: 0e2477b6c3c41d8f5bef8bf3dab17704d5a9445d1990035bd2c5105904c795d06d1a9b4038af2b6d932b35bd3c3e71abeae17d39762d9647e78287f789cf9283

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
